openapi: 3.0.3
info:
  title: Sample Vendor API
  version: 1.0.0
  description: Simple demo API for bump.sh POC (no relation to production apps)
servers:
  - url: https://api.example.com
    description: Production
components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: X-API-Key
security:
  - ApiKeyAuth: []
paths:
  /health:
    get:
      summary: Health check
      responses:
        '200':
          description: OK
          content:
            application/json:
              example:
                status: ok
  /items:
    get:
      summary: List items
      parameters:
        - in: query
          name: limit
          schema:
            type: integer
            minimum: 1
            maximum: 100
          required: false
          description: Max items to return (default 25)
      responses:
        '200':
          description: List
          content:
            application/json:
              example:
                items:
                  - id: it_123
                    name: Widget
  /items/{id}:
    get:
      summary: Get item by ID
      parameters:
        - in: path
          name: id
          schema:
            type: string
          required: true
      responses:
        '200':
          description: Found
          content:
            application/json:
              example:
                id: it_123
                name: Widget
        '404':
          description: Not found