const express = require('express');
const cors = require('cors');
const purchaseRoutes = require('./routes/purchaseRoutes');
const salesRoutes = require('./routes/salesRoutes');
const paymentRoutes = require('./routes/paymentRoutes');
const productRoutes = require('./routes/productRoutes');
const customerRoutes = require('./routes/customerRoutes');
const supplierRoutes = require('./routes/supplierRoutes');
const dashboardRoutes = require('./routes/dashboardRoutes');
const reportRoutes = require('./routes/reportRoutes');
const creditRoutes = require('./routes/creditRoutes');
const adjustmentRoutes = require('./routes/adjustmentRoutes');
const inventoryRoutes = require('./routes/inventoryRoutes');
const locationRoutes = require('./routes/locationRoutes');
const metalRoutes = require('./routes/metalRoutes');
const pricingRoutes = require('./routes/pricingRoutes');
const vendorRoutes = require('./routes/vendorRoutes');
const adminRoutes = require('./routes/adminRoutes');
const routeRoutes = require('./routes/routeRoutes');
const routeTripRoutes = require('./routes/routeTripRoutes');

const app = express();
const ensureSchema = require('./db/ensureSchema');
const seedDefaults = require('./db/seedDefaults');
app.use(cors());
app.use(express.json());

ensureSchema().then(()=>seedDefaults()).catch(()=>{});
app.use('/purchases', purchaseRoutes);
app.use('/sales', salesRoutes);
app.use('/payments', paymentRoutes);
app.use('/products', productRoutes);
app.use('/customers', customerRoutes);
app.use('/suppliers', supplierRoutes);
app.use('/dashboard', dashboardRoutes);
app.use('/reports', reportRoutes);
app.use('/credit-summary', creditRoutes);
app.use('/stock-adjustments', adjustmentRoutes);
app.use('/inventory', inventoryRoutes);
app.use('/locations', locationRoutes);
app.use('/metal-master', metalRoutes);
app.use('/pricing-master', pricingRoutes);
app.use('/vendors', vendorRoutes);
app.use('/admin', adminRoutes);
app.use('/routes', routeRoutes);
app.use('/route-trips', routeTripRoutes);

app.get('/', (req, res) => res.send('Egg Retail Shop Backend Running'));
module.exports = app;